### ISSUE TITLE
Expression parser with first, second, third needs refactoring

### ISSUE THREAD

**Issue by sjcjoosten** [jschlachtenhaufen/calculus-parser#1]
The code in ``Expressions.hs`` needs to be re-thought a bit:

the code of expr parses a first factor (good idea), and then passes it. However, it passes it to all of 'third', 'second' and 'first'. I'm not sure what the idea is behind passing it to all of those, it might be a good idea depending on what those functions mean, but you seem to be of multiple thoughts there: ``second`` has ``third e1` ` as a fallback, whereas the other do not have fallbacks, and I don't really see why you would need a fallback.

Let's simplify things, and say you have three operators: comma, times and power written ,*^ respectively, precedence low to high, and your constants are numbers. Here's an expression:

```
5 * 6  ,  7^8 * 9 * 0^1  ,  2 * 3
```

I (as a human parser) see this as a list of three elements. So the first thing I look at is the operator with the lowest precedence, which is what 'first' does. I'd define ``expr = secondThing >>= first``. What is a ``secondThing``?

```
7^8 * 9 * 0^1
```

Again I see three things, so I suppose that ``secondThing = thirdThing >>= second``, with ``thirdThing`` defined as ``factor >>= third`` to complete the pattern. Inlining the definitions of ``secondThing`` and ``thirdThing`` gives ``expr = factor >>= third >>= second >>= first``, which is what you have, so that makes sense to me.

Applying this way of seeing things, ``first`` needs to combine ``secondThing``s with `,` operators. That means line 25 needs to parse ``secondThing``s, not ``factor >>= second``. The change made to line 31, adding the ``<|> third e1`` as a choice, is perhaps there to fix this error? If so, perhaps you had a different solution to the same problem in mind when you applied that fix.

There are several equivalent ways to write this code, and each comes with a different story. Tell that story in the comments of your code and it might be possible for me to see what error you made when you wrote the code. So far, I can only point out these two inconsistencies.

**Comment by jschlachtenhaufen** [comment]
Thanks for the feedback. To clarify, as far as we can tell, our current expression parsing code works correctly, including parsing operators in order of precedence. I'll remove that section from the readme, since now our trouble is more with substituting subexpressions in the context of the parent expression. With that said, we will definitely revisit the expression parsing code to clean it up / add comments explaining the logic

**Comment by sjcjoosten** [comment]
Glad to hear it's working for you, I'll leave it to you to close this issue

**Comment by jschlachtenhaufen** [comment]
Will do. I'm not sure if you saw Ryan's email, but do you have any suggestions regarding that subexpression substitution problems we're having outlined in the readme?

**Comment by sjcjoosten** [comment]
I did, part of it read:

```
John and I have made some progress on our project but are stuck on a point that we discussed briefly in office hours. We have documented our progress in the README. We are both busy until tonight so if you have any time to look that over and give us some advice that would be great.
```

which has lead me to create this issue...

**Comment by jschlachtenhaufen** [comment]
Ah I see, sorry for the confusion - we should have removed the README section about our old parsing issues. Thanks again for all the help!
